# Generated by Django 5.2.14 on 2026-06-10 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_workspace_workspacemembership_workspace_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('file_size_bytes', models.BigIntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='api.workspace')),
            ],
            options={
                'unique_together': {('workspace', 'source')},
            },
        ),
    ]
